{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./env.nix
    ./home-manager.nix
    ./graphics.nix
    ./kernel.nix
    ./mime.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./timezone.nix
    ./user.nix
    ./zram.nix
    ./nm-applet.nix
    ./nvim.nix
    ./v2raya.nix
    ./fcitx5.nix
    ./vbox.nix
    ./flatpak.nix
    ./ld.nix
    ./ssh.nix
  ];
}
